[package]
name = "libgleam"
version = "0.2.0"
build = "build.rs"
authors = ["feenk gmbh. <contact@feenk.com>"]
edition = "2021"

[dependencies]
gleam = "0.14"
value-box = "1.1"
string-box = "1.1"
array-box = "1.0"

[build-dependencies]
gl_generator = "0.14"

[lib]
name = "Gleam"
crate-type = ["cdylib"]